version: '3.8'

services:
  webapi:
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=clinicaintegradadb;User=root;Password=Teste1@2"
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "8080:8080"
